document:
  name: pagoPA, PdA ManualeUtente
  description: |
    Lo scopo di questo documento è quello di descrivere le funzionalità che
    il “Portale delle Adesioni”, predisposto da AgID al fine di supportare
    gli Enti Creditori nel processo di adesione a pagoPA, mette a
    disposizione dei soggetti che, con diversi ruoli, intervengono in tale
    processo: i soggetti incaricati dagli Enti Creditori, le figure tecniche
    dei soggetti direttamente connessi al Nodo, gli operatori del Nodo dei
    Pagamenti-SPC e dell’Agenzia per l’Italia Digitale  
  tags:
    - SANP
    - pagoPA
    - PA
    - AgID
